name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Install Tesseract with chi_sim
        run: |
          choco install tesseract --version=5.3.1.20230401 -y
          curl -L -o chi_sim.traineddata https://github.com/tesseract-ocr/tessdata/raw/main/chi_sim.traineddata
          move chi_sim.traineddata "C:\ProgramData\chocolatey\lib\tesseract\tools\tesseract-ocr\tessdata\chi_sim.traineddata"

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile --windowed wechat_monitor_pro.py

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wechat-monitor-exe
          path: dist/wechat_monitor_pro.exe
