name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Install Tesseract OCR
      run: choco install tesseract -y

    - name: Download chi_sim language data
      run: |
        Invoke-WebRequest -Uri https://github.com/tesseract-ocr/tessdata/raw/main/chi_sim.traineddata -OutFile chi_sim.traineddata
        $tessdataPath = "C:\Program Files\Tesseract-OCR\tessdata"
        if (!(Test-Path $tessdataPath)) {
            New-Item -ItemType Directory -Path $tessdataPath
        }
        Move-Item -Path "chi_sim.traineddata" -Destination $tessdataPath

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconfirm --windowed --icon=icon.ico wechat_monitor_pro.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: wechat-monitor-exe
        path: dist/wechat_monitor_pro/
