name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Install Tesseract-OCR
        run: |
          choco install tesseract -y
          refreshenv

      - name: Add chi_sim language for Tesseract
        run: |
          Invoke-WebRequest -Uri https://github.com/tesseract-ocr/tessdata/raw/main/chi_sim.traineddata -OutFile chi_sim.traineddata
          Move-Item chi_sim.traineddata "C:\ProgramData\chocolatey\lib\tesseract\tools\tesseract-OCR\tessdata\"

      - name: Build EXE with PyInstaller (no icon)
        run: pyinstaller --noconfirm --windowed wechat_monitor_pro.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wechat_monitor_pro_exe
          path: dist/wechat_monitor_pro.exe
